echo '[build]
builder = "NIXPACKS"

[build.nixpacks]
aptPackages = [
    "tesseract-ocr",
    "tesseract-ocr-eng", 
    "tesseract-ocr-hin",
    "libgl1-mesa-glx",
    "libglib2.0-0",
    "libsm6",
    "libxext6",
    "libxrender-dev",
    "libgomp1"
]' > railway.toml
